name: Build and Publish
on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: manoadamro/rust-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
